<?php

namespace App\Http\Requests\news;

use Illuminate\Foundation\Http\FormRequest;

class UpdateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules():array
    {
        return [
            'categories_id' => ['required', 'integer', 'min:1'],
            'title' => ['required','string', 'min:5', 'max:200'],
            'author' =>  ['required','string', 'min:5', 'max:200'],
            'img' => ['nullable', 'image'],
            'status' => ['required'],
            'description' => ['required','string', 'min:50']
        ];
    }

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
//        Можем переопределить сообщение:
//        return [
//            'required' => 'сообщение :attribute'
//        ];
    }

    public function attributes()
    {
        return parent::attributes(); // TODO: Change the autogenerated stub
//        return [
//            'title' => 'наименование'
//        ];

    }
}
